<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('integrations', function (Blueprint $table): void {
            $table->id();
            $table->uuid('uuid')->unique();
            $table->foreignId('team_id')->constrained()->cascadeOnDelete();
            $table->string('provider', 20);
            $table->string('name', 120);
            $table->string('base_url', 255)->nullable();
            // encrypted:array cast. Never logged, never returned by the API.
            $table->text('credentials')->nullable();
            // Generated by us and given to the provider, not the reverse.
            $table->string('webhook_secret', 128);
            $table->jsonb('scopes')->default('[]');
            $table->string('status', 20)->default('pending');
            $table->timestampTz('last_verified_at')->nullable();
            $table->timestampTz('last_event_at')->nullable();
            $table->text('last_error')->nullable();
            $table->jsonb('settings')->default('{}');
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestampsTz();
            $table->softDeletesTz();
        });

        DB::statement('ALTER TABLE integrations ALTER COLUMN uuid SET DEFAULT uuid_generate_v4()');
        DB::statement("ALTER TABLE integrations ADD CONSTRAINT chk_integrations_provider
            CHECK (provider IN ('gitlab','github','jenkins','generic'))");
        DB::statement("ALTER TABLE integrations ADD CONSTRAINT chk_integrations_status
            CHECK (status IN ('pending','active','error','disabled'))");
        DB::statement('CREATE INDEX idx_integrations_team ON integrations(team_id) WHERE deleted_at IS NULL');
    }

    public function down(): void
    {
        Schema::dropIfExists('integrations');
    }
};
